/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const RepairAction = IDL.Record({
  'field' : IDL.Text,
  'description' : IDL.Text,
  'repair_type' : IDL.Text,
});
export const ApiEndpoint = IDL.Record({
  'method' : IDL.Text,
  'response_type' : IDL.Text,
  'path' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'auth_required' : IDL.Bool,
  'request_body' : IDL.Opt(IDL.Text),
});
export const ApiSchema = IDL.Record({ 'endpoints' : IDL.Vec(ApiEndpoint) });
export const AuthSchema = IDL.Record({
  'protected_routes' : IDL.Vec(IDL.Text),
  'strategy' : IDL.Text,
  'providers' : IDL.Vec(IDL.Text),
  'session_type' : IDL.Text,
});
export const FieldType = IDL.Text;
export const FieldName = IDL.Text;
export const EntityField = IDL.Record({
  'field_type' : FieldType,
  'name' : FieldName,
  'unique' : IDL.Bool,
  'required' : IDL.Bool,
});
export const Relationship = IDL.Record({
  'field' : FieldName,
  'rel_type' : IDL.Text,
  'target' : IDL.Text,
});
export const Entity = IDL.Record({
  'name' : IDL.Text,
  'fields' : IDL.Vec(EntityField),
  'relationships' : IDL.Vec(Relationship),
});
export const DbColumn = IDL.Record({
  'constraints' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'col_type' : IDL.Text,
});
export const DbTable = IDL.Record({
  'foreign_keys' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'indexes' : IDL.Vec(IDL.Text),
  'columns' : IDL.Vec(DbColumn),
});
export const DatabaseSchema = IDL.Record({ 'tables' : IDL.Vec(DbTable) });
export const AppName = IDL.Text;
export const Page = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'components' : IDL.Vec(IDL.Text),
  'route' : IDL.Text,
  'auth_required' : IDL.Bool,
});
export const Role = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'parent_role' : IDL.Opt(IDL.Text),
});
export const BusinessRule = IDL.Record({
  'action' : IDL.Text,
  'description' : IDL.Text,
  'rule_id' : IDL.Text,
  'condition' : IDL.Text,
});
export const AppConfig = IDL.Record({
  'api' : ApiSchema,
  'auth' : AuthSchema,
  'entities' : IDL.Vec(Entity),
  'database' : DatabaseSchema,
  'app_name' : AppName,
  'pages' : IDL.Vec(Page),
  'roles' : IDL.Vec(Role),
  'business_rules' : IDL.Vec(BusinessRule),
});
export const RepairResult = IDL.Record({
  'repairs_made' : IDL.Vec(RepairAction),
  'is_valid' : IDL.Bool,
  'final_config' : AppConfig,
});
export const RefinementChange = IDL.Record({
  'affected_field' : IDL.Text,
  'description' : IDL.Text,
  'change_type' : IDL.Text,
});
export const RefinementResult = IDL.Record({
  'changes_made' : IDL.Vec(RefinementChange),
  'config' : AppConfig,
});
export const UiComponent = IDL.Record({
  'name' : IDL.Text,
  'component_type' : IDL.Text,
  'props' : IDL.Vec(IDL.Text),
});
export const UiPage = IDL.Record({
  'page_name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'layout' : IDL.Text,
  'components' : IDL.Vec(UiComponent),
  'route' : IDL.Text,
  'auth_required' : IDL.Bool,
});
export const UiSchema = IDL.Record({
  'navigation' : IDL.Vec(IDL.Text),
  'pages' : IDL.Vec(UiPage),
});
export const SchemaGenerationResult = IDL.Record({
  'auth_schema' : AuthSchema,
  'api_schema' : ApiSchema,
  'ui_schema' : UiSchema,
  'database_schema' : DatabaseSchema,
});
export const RoleHierarchyEntry = IDL.Record({
  'permissions' : IDL.Vec(IDL.Text),
  'role_name' : IDL.Text,
  'parent_role' : IDL.Opt(IDL.Text),
});
export const ArchitectureLayer = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const ArchitectureModel = IDL.Record({
  'pattern' : IDL.Text,
  'layers' : IDL.Vec(ArchitectureLayer),
});
export const UserFlow = IDL.Record({
  'steps' : IDL.Vec(IDL.Text),
  'flow_name' : IDL.Text,
});
export const SystemDesignResult = IDL.Record({
  'application_structure' : IDL.Vec(IDL.Text),
  'role_hierarchy' : IDL.Vec(RoleHierarchyEntry),
  'architecture_model' : ArchitectureModel,
  'user_flows' : IDL.Vec(UserFlow),
});
export const IntentExtractionResult = IDL.Record({
  'apis' : IDL.Vec(ApiEndpoint),
  'entities' : IDL.Vec(Entity),
  'assumptions' : IDL.Vec(IDL.Text),
  'pages' : IDL.Vec(Page),
  'roles' : IDL.Vec(Role),
  'business_rules' : IDL.Vec(BusinessRule),
});
export const ValidationError = IDL.Record({
  'field' : IDL.Opt(IDL.Text),
  'message' : IDL.Text,
  'severity' : IDL.Text,
  'error_code' : IDL.Text,
});
export const ValidationResult = IDL.Record({
  'errors' : IDL.Vec(ValidationError),
  'is_valid' : IDL.Bool,
  'warnings' : IDL.Vec(ValidationError),
  'config' : IDL.Opt(AppConfig),
});
export const CompileResult = IDL.Record({
  'repair' : IDL.Opt(RepairResult),
  'refinement' : IDL.Opt(RefinementResult),
  'error_message' : IDL.Opt(IDL.Text),
  'schemas' : IDL.Opt(SchemaGenerationResult),
  'design' : IDL.Opt(SystemDesignResult),
  'processing_time_ms' : IDL.Nat,
  'intent' : IDL.Opt(IntentExtractionResult),
  'assumptions' : IDL.Vec(IDL.Text),
  'success' : IDL.Bool,
  'validation' : IDL.Opt(ValidationResult),
  'final_config' : IDL.Opt(AppConfig),
});
export const DeploymentCheck = IDL.Record({
  'detail' : IDL.Text,
  'check_name' : IDL.Text,
  'passed' : IDL.Bool,
});
export const DeploymentReport = IDL.Record({
  'status' : IDL.Text,
  'warnings' : IDL.Vec(IDL.Text),
  'checks' : IDL.Vec(DeploymentCheck),
  'readiness_score' : IDL.Nat,
});
export const FailureType = IDL.Record({
  'type_name' : IDL.Text,
  'count' : IDL.Nat,
});
export const MetricsResult = IDL.Record({
  'failure_types' : IDL.Vec(FailureType),
  'total_compilations' : IDL.Nat,
  'repairs_made_total' : IDL.Nat,
  'successful_compilations' : IDL.Nat,
  'average_processing_time_ms' : IDL.Nat,
  'validation_errors_total' : IDL.Nat,
});

export const idlService = IDL.Service({
  'compile' : IDL.Func([IDL.Text], [CompileResult], []),
  'execute' : IDL.Func([IDL.Text], [DeploymentReport], []),
  'getMetrics' : IDL.Func([], [MetricsResult], ['query']),
  'repair' : IDL.Func([IDL.Text], [RepairResult], []),
  'runBenchmark' : IDL.Func([IDL.Nat], [CompileResult], []),
  'validate' : IDL.Func([IDL.Text], [ValidationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const RepairAction = IDL.Record({
    'field' : IDL.Text,
    'description' : IDL.Text,
    'repair_type' : IDL.Text,
  });
  const ApiEndpoint = IDL.Record({
    'method' : IDL.Text,
    'response_type' : IDL.Text,
    'path' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'auth_required' : IDL.Bool,
    'request_body' : IDL.Opt(IDL.Text),
  });
  const ApiSchema = IDL.Record({ 'endpoints' : IDL.Vec(ApiEndpoint) });
  const AuthSchema = IDL.Record({
    'protected_routes' : IDL.Vec(IDL.Text),
    'strategy' : IDL.Text,
    'providers' : IDL.Vec(IDL.Text),
    'session_type' : IDL.Text,
  });
  const FieldType = IDL.Text;
  const FieldName = IDL.Text;
  const EntityField = IDL.Record({
    'field_type' : FieldType,
    'name' : FieldName,
    'unique' : IDL.Bool,
    'required' : IDL.Bool,
  });
  const Relationship = IDL.Record({
    'field' : FieldName,
    'rel_type' : IDL.Text,
    'target' : IDL.Text,
  });
  const Entity = IDL.Record({
    'name' : IDL.Text,
    'fields' : IDL.Vec(EntityField),
    'relationships' : IDL.Vec(Relationship),
  });
  const DbColumn = IDL.Record({
    'constraints' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'col_type' : IDL.Text,
  });
  const DbTable = IDL.Record({
    'foreign_keys' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'indexes' : IDL.Vec(IDL.Text),
    'columns' : IDL.Vec(DbColumn),
  });
  const DatabaseSchema = IDL.Record({ 'tables' : IDL.Vec(DbTable) });
  const AppName = IDL.Text;
  const Page = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'components' : IDL.Vec(IDL.Text),
    'route' : IDL.Text,
    'auth_required' : IDL.Bool,
  });
  const Role = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'parent_role' : IDL.Opt(IDL.Text),
  });
  const BusinessRule = IDL.Record({
    'action' : IDL.Text,
    'description' : IDL.Text,
    'rule_id' : IDL.Text,
    'condition' : IDL.Text,
  });
  const AppConfig = IDL.Record({
    'api' : ApiSchema,
    'auth' : AuthSchema,
    'entities' : IDL.Vec(Entity),
    'database' : DatabaseSchema,
    'app_name' : AppName,
    'pages' : IDL.Vec(Page),
    'roles' : IDL.Vec(Role),
    'business_rules' : IDL.Vec(BusinessRule),
  });
  const RepairResult = IDL.Record({
    'repairs_made' : IDL.Vec(RepairAction),
    'is_valid' : IDL.Bool,
    'final_config' : AppConfig,
  });
  const RefinementChange = IDL.Record({
    'affected_field' : IDL.Text,
    'description' : IDL.Text,
    'change_type' : IDL.Text,
  });
  const RefinementResult = IDL.Record({
    'changes_made' : IDL.Vec(RefinementChange),
    'config' : AppConfig,
  });
  const UiComponent = IDL.Record({
    'name' : IDL.Text,
    'component_type' : IDL.Text,
    'props' : IDL.Vec(IDL.Text),
  });
  const UiPage = IDL.Record({
    'page_name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'layout' : IDL.Text,
    'components' : IDL.Vec(UiComponent),
    'route' : IDL.Text,
    'auth_required' : IDL.Bool,
  });
  const UiSchema = IDL.Record({
    'navigation' : IDL.Vec(IDL.Text),
    'pages' : IDL.Vec(UiPage),
  });
  const SchemaGenerationResult = IDL.Record({
    'auth_schema' : AuthSchema,
    'api_schema' : ApiSchema,
    'ui_schema' : UiSchema,
    'database_schema' : DatabaseSchema,
  });
  const RoleHierarchyEntry = IDL.Record({
    'permissions' : IDL.Vec(IDL.Text),
    'role_name' : IDL.Text,
    'parent_role' : IDL.Opt(IDL.Text),
  });
  const ArchitectureLayer = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const ArchitectureModel = IDL.Record({
    'pattern' : IDL.Text,
    'layers' : IDL.Vec(ArchitectureLayer),
  });
  const UserFlow = IDL.Record({
    'steps' : IDL.Vec(IDL.Text),
    'flow_name' : IDL.Text,
  });
  const SystemDesignResult = IDL.Record({
    'application_structure' : IDL.Vec(IDL.Text),
    'role_hierarchy' : IDL.Vec(RoleHierarchyEntry),
    'architecture_model' : ArchitectureModel,
    'user_flows' : IDL.Vec(UserFlow),
  });
  const IntentExtractionResult = IDL.Record({
    'apis' : IDL.Vec(ApiEndpoint),
    'entities' : IDL.Vec(Entity),
    'assumptions' : IDL.Vec(IDL.Text),
    'pages' : IDL.Vec(Page),
    'roles' : IDL.Vec(Role),
    'business_rules' : IDL.Vec(BusinessRule),
  });
  const ValidationError = IDL.Record({
    'field' : IDL.Opt(IDL.Text),
    'message' : IDL.Text,
    'severity' : IDL.Text,
    'error_code' : IDL.Text,
  });
  const ValidationResult = IDL.Record({
    'errors' : IDL.Vec(ValidationError),
    'is_valid' : IDL.Bool,
    'warnings' : IDL.Vec(ValidationError),
    'config' : IDL.Opt(AppConfig),
  });
  const CompileResult = IDL.Record({
    'repair' : IDL.Opt(RepairResult),
    'refinement' : IDL.Opt(RefinementResult),
    'error_message' : IDL.Opt(IDL.Text),
    'schemas' : IDL.Opt(SchemaGenerationResult),
    'design' : IDL.Opt(SystemDesignResult),
    'processing_time_ms' : IDL.Nat,
    'intent' : IDL.Opt(IntentExtractionResult),
    'assumptions' : IDL.Vec(IDL.Text),
    'success' : IDL.Bool,
    'validation' : IDL.Opt(ValidationResult),
    'final_config' : IDL.Opt(AppConfig),
  });
  const DeploymentCheck = IDL.Record({
    'detail' : IDL.Text,
    'check_name' : IDL.Text,
    'passed' : IDL.Bool,
  });
  const DeploymentReport = IDL.Record({
    'status' : IDL.Text,
    'warnings' : IDL.Vec(IDL.Text),
    'checks' : IDL.Vec(DeploymentCheck),
    'readiness_score' : IDL.Nat,
  });
  const FailureType = IDL.Record({ 'type_name' : IDL.Text, 'count' : IDL.Nat });
  const MetricsResult = IDL.Record({
    'failure_types' : IDL.Vec(FailureType),
    'total_compilations' : IDL.Nat,
    'repairs_made_total' : IDL.Nat,
    'successful_compilations' : IDL.Nat,
    'average_processing_time_ms' : IDL.Nat,
    'validation_errors_total' : IDL.Nat,
  });
  
  return IDL.Service({
    'compile' : IDL.Func([IDL.Text], [CompileResult], []),
    'execute' : IDL.Func([IDL.Text], [DeploymentReport], []),
    'getMetrics' : IDL.Func([], [MetricsResult], ['query']),
    'repair' : IDL.Func([IDL.Text], [RepairResult], []),
    'runBenchmark' : IDL.Func([IDL.Nat], [CompileResult], []),
    'validate' : IDL.Func([IDL.Text], [ValidationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };