/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ApiEndpoint {
  'method' : string,
  'response_type' : string,
  'path' : string,
  'role' : [] | [string],
  'auth_required' : boolean,
  'request_body' : [] | [string],
}
export interface ApiSchema { 'endpoints' : Array<ApiEndpoint> }
export interface AppConfig {
  'api' : ApiSchema,
  'auth' : AuthSchema,
  'entities' : Array<Entity>,
  'database' : DatabaseSchema,
  'app_name' : AppName,
  'pages' : Array<Page>,
  'roles' : Array<Role>,
  'business_rules' : Array<BusinessRule>,
}
export type AppName = string;
export interface ArchitectureLayer { 'name' : string, 'description' : string }
export interface ArchitectureModel {
  'pattern' : string,
  'layers' : Array<ArchitectureLayer>,
}
export interface AuthSchema {
  'protected_routes' : Array<string>,
  'strategy' : string,
  'providers' : Array<string>,
  'session_type' : string,
}
export interface BusinessRule {
  'action' : string,
  'description' : string,
  'rule_id' : string,
  'condition' : string,
}
export interface CompileResult {
  'repair' : [] | [RepairResult],
  'refinement' : [] | [RefinementResult],
  'error_message' : [] | [string],
  'schemas' : [] | [SchemaGenerationResult],
  'design' : [] | [SystemDesignResult],
  'processing_time_ms' : bigint,
  'intent' : [] | [IntentExtractionResult],
  'assumptions' : Array<string>,
  'success' : boolean,
  'validation' : [] | [ValidationResult],
  'final_config' : [] | [AppConfig],
}
export interface DatabaseSchema { 'tables' : Array<DbTable> }
export interface DbColumn {
  'constraints' : Array<string>,
  'name' : string,
  'col_type' : string,
}
export interface DbTable {
  'foreign_keys' : Array<string>,
  'name' : string,
  'indexes' : Array<string>,
  'columns' : Array<DbColumn>,
}
export interface DeploymentCheck {
  'detail' : string,
  'check_name' : string,
  'passed' : boolean,
}
export interface DeploymentReport {
  'status' : string,
  'warnings' : Array<string>,
  'checks' : Array<DeploymentCheck>,
  'readiness_score' : bigint,
}
export interface Entity {
  'name' : string,
  'fields' : Array<EntityField>,
  'relationships' : Array<Relationship>,
}
export interface EntityField {
  'field_type' : FieldType,
  'name' : FieldName,
  'unique' : boolean,
  'required' : boolean,
}
export interface FailureType { 'type_name' : string, 'count' : bigint }
export type FieldName = string;
export type FieldType = string;
export interface IntentExtractionResult {
  'apis' : Array<ApiEndpoint>,
  'entities' : Array<Entity>,
  'assumptions' : Array<string>,
  'pages' : Array<Page>,
  'roles' : Array<Role>,
  'business_rules' : Array<BusinessRule>,
}
export interface MetricsResult {
  'failure_types' : Array<FailureType>,
  'total_compilations' : bigint,
  'repairs_made_total' : bigint,
  'successful_compilations' : bigint,
  'average_processing_time_ms' : bigint,
  'validation_errors_total' : bigint,
}
export interface Page {
  'name' : string,
  'role' : [] | [string],
  'components' : Array<string>,
  'route' : string,
  'auth_required' : boolean,
}
export interface RefinementChange {
  'affected_field' : string,
  'description' : string,
  'change_type' : string,
}
export interface RefinementResult {
  'changes_made' : Array<RefinementChange>,
  'config' : AppConfig,
}
export interface Relationship {
  'field' : FieldName,
  'rel_type' : string,
  'target' : string,
}
export interface RepairAction {
  'field' : string,
  'description' : string,
  'repair_type' : string,
}
export interface RepairResult {
  'repairs_made' : Array<RepairAction>,
  'is_valid' : boolean,
  'final_config' : AppConfig,
}
export interface Role {
  'permissions' : Array<string>,
  'name' : string,
  'parent_role' : [] | [string],
}
export interface RoleHierarchyEntry {
  'permissions' : Array<string>,
  'role_name' : string,
  'parent_role' : [] | [string],
}
export interface SchemaGenerationResult {
  'auth_schema' : AuthSchema,
  'api_schema' : ApiSchema,
  'ui_schema' : UiSchema,
  'database_schema' : DatabaseSchema,
}
export interface SystemDesignResult {
  'application_structure' : Array<string>,
  'role_hierarchy' : Array<RoleHierarchyEntry>,
  'architecture_model' : ArchitectureModel,
  'user_flows' : Array<UserFlow>,
}
export interface UiComponent {
  'name' : string,
  'component_type' : string,
  'props' : Array<string>,
}
export interface UiPage {
  'page_name' : string,
  'role' : [] | [string],
  'layout' : string,
  'components' : Array<UiComponent>,
  'route' : string,
  'auth_required' : boolean,
}
export interface UiSchema {
  'navigation' : Array<string>,
  'pages' : Array<UiPage>,
}
export interface UserFlow { 'steps' : Array<string>, 'flow_name' : string }
export interface ValidationError {
  'field' : [] | [string],
  'message' : string,
  'severity' : string,
  'error_code' : string,
}
export interface ValidationResult {
  'errors' : Array<ValidationError>,
  'is_valid' : boolean,
  'warnings' : Array<ValidationError>,
  'config' : [] | [AppConfig],
}
export interface _SERVICE {
  'compile' : ActorMethod<[string], CompileResult>,
  'execute' : ActorMethod<[string], DeploymentReport>,
  'getMetrics' : ActorMethod<[], MetricsResult>,
  'repair' : ActorMethod<[string], RepairResult>,
  'runBenchmark' : ActorMethod<[bigint], CompileResult>,
  'validate' : ActorMethod<[string], ValidationResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];