/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RefinementResult {
    changes_made: Array<RefinementChange>;
    config: AppConfig;
}
export interface Relationship {
    field: FieldName;
    rel_type: string;
    target: string;
}
export interface MetricsResult {
    failure_types: Array<FailureType>;
    total_compilations: bigint;
    repairs_made_total: bigint;
    successful_compilations: bigint;
    average_processing_time_ms: bigint;
    validation_errors_total: bigint;
}
export interface AppConfig {
    api: ApiSchema;
    auth: AuthSchema;
    entities: Array<Entity>;
    database: DatabaseSchema;
    app_name: AppName;
    pages: Array<Page>;
    roles: Array<Role>;
    business_rules: Array<BusinessRule>;
}
export interface RepairAction {
    field: string;
    description: string;
    repair_type: string;
}
export interface UiPage {
    page_name: string;
    role?: string;
    layout: string;
    components: Array<UiComponent>;
    route: string;
    auth_required: boolean;
}
export type AppName = string;
export interface ArchitectureLayer {
    name: string;
    description: string;
}
export interface DeploymentCheck {
    detail: string;
    check_name: string;
    passed: boolean;
}
export interface AuthSchema {
    protected_routes: Array<string>;
    strategy: string;
    providers: Array<string>;
    session_type: string;
}
export interface Role {
    permissions: Array<string>;
    name: string;
    parent_role?: string;
}
export interface UserFlow {
    steps: Array<string>;
    flow_name: string;
}
export interface SchemaGenerationResult {
    auth_schema: AuthSchema;
    api_schema: ApiSchema;
    ui_schema: UiSchema;
    database_schema: DatabaseSchema;
}
export interface RepairResult {
    repairs_made: Array<RepairAction>;
    is_valid: boolean;
    final_config: AppConfig;
}
export interface FailureType {
    type_name: string;
    count: bigint;
}
export interface Page {
    name: string;
    role?: string;
    components: Array<string>;
    route: string;
    auth_required: boolean;
}
export interface Entity {
    name: string;
    fields: Array<EntityField>;
    relationships: Array<Relationship>;
}
export interface DbTable {
    foreign_keys: Array<string>;
    name: string;
    indexes: Array<string>;
    columns: Array<DbColumn>;
}
export interface DatabaseSchema {
    tables: Array<DbTable>;
}
export interface CompileResult {
    repair?: RepairResult;
    refinement?: RefinementResult;
    error_message?: string;
    schemas?: SchemaGenerationResult;
    design?: SystemDesignResult;
    processing_time_ms: bigint;
    intent?: IntentExtractionResult;
    assumptions: Array<string>;
    success: boolean;
    validation?: ValidationResult;
    final_config?: AppConfig;
}
export interface BusinessRule {
    action: string;
    description: string;
    rule_id: string;
    condition: string;
}
export interface UiComponent {
    name: string;
    component_type: string;
    props: Array<string>;
}
export interface ApiSchema {
    endpoints: Array<ApiEndpoint>;
}
export interface DeploymentReport {
    status: string;
    warnings: Array<string>;
    checks: Array<DeploymentCheck>;
    readiness_score: bigint;
}
export type FieldName = string;
export interface ArchitectureModel {
    pattern: string;
    layers: Array<ArchitectureLayer>;
}
export interface DbColumn {
    constraints: Array<string>;
    name: string;
    col_type: string;
}
export interface RoleHierarchyEntry {
    permissions: Array<string>;
    role_name: string;
    parent_role?: string;
}
export interface IntentExtractionResult {
    apis: Array<ApiEndpoint>;
    entities: Array<Entity>;
    assumptions: Array<string>;
    pages: Array<Page>;
    roles: Array<Role>;
    business_rules: Array<BusinessRule>;
}
export interface UiSchema {
    navigation: Array<string>;
    pages: Array<UiPage>;
}
export interface ValidationError {
    field?: string;
    message: string;
    severity: string;
    error_code: string;
}
export interface RefinementChange {
    affected_field: string;
    description: string;
    change_type: string;
}
export type FieldType = string;
export interface ValidationResult {
    errors: Array<ValidationError>;
    is_valid: boolean;
    warnings: Array<ValidationError>;
    config?: AppConfig;
}
export interface SystemDesignResult {
    application_structure: Array<string>;
    role_hierarchy: Array<RoleHierarchyEntry>;
    architecture_model: ArchitectureModel;
    user_flows: Array<UserFlow>;
}
export interface ApiEndpoint {
    method: string;
    response_type: string;
    path: string;
    role?: string;
    auth_required: boolean;
    request_body?: string;
}
export interface EntityField {
    field_type: FieldType;
    name: FieldName;
    unique: boolean;
    required: boolean;
}
export interface backendInterface {
    compile(prompt: string): Promise<CompileResult>;
    execute(config_json: string): Promise<DeploymentReport>;
    getMetrics(): Promise<MetricsResult>;
    repair(config_json: string): Promise<RepairResult>;
    runBenchmark(prompt_index: bigint): Promise<CompileResult>;
    validate(config_json: string): Promise<ValidationResult>;
}
import type { ApiEndpoint as _ApiEndpoint, ApiSchema as _ApiSchema, AppConfig as _AppConfig, AppName as _AppName, ArchitectureModel as _ArchitectureModel, AuthSchema as _AuthSchema, BusinessRule as _BusinessRule, CompileResult as _CompileResult, DatabaseSchema as _DatabaseSchema, Entity as _Entity, IntentExtractionResult as _IntentExtractionResult, Page as _Page, RefinementChange as _RefinementChange, RefinementResult as _RefinementResult, RepairAction as _RepairAction, RepairResult as _RepairResult, Role as _Role, RoleHierarchyEntry as _RoleHierarchyEntry, SchemaGenerationResult as _SchemaGenerationResult, SystemDesignResult as _SystemDesignResult, UiComponent as _UiComponent, UiPage as _UiPage, UiSchema as _UiSchema, UserFlow as _UserFlow, ValidationError as _ValidationError, ValidationResult as _ValidationResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async compile(arg0: string): Promise<CompileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.compile(arg0);
                return from_candid_CompileResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.compile(arg0);
            return from_candid_CompileResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async execute(arg0: string): Promise<DeploymentReport> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return result;
        }
    }
    async getMetrics(): Promise<MetricsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMetrics();
            return result;
        }
    }
    async repair(arg0: string): Promise<RepairResult> {
        if (this.processError) {
            try {
                const result = await this.actor.repair(arg0);
                return from_candid_RepairResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.repair(arg0);
            return from_candid_RepairResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async runBenchmark(arg0: bigint): Promise<CompileResult> {
        if (this.processError) {
            try {
                const result = await this.actor.runBenchmark(arg0);
                return from_candid_CompileResult_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runBenchmark(arg0);
            return from_candid_CompileResult_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async validate(arg0: string): Promise<ValidationResult> {
        if (this.processError) {
            try {
                const result = await this.actor.validate(arg0);
                return from_candid_ValidationResult_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validate(arg0);
            return from_candid_ValidationResult_n41(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApiEndpoint_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiEndpoint): ApiEndpoint {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ApiSchema_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApiSchema): ApiSchema {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_AppConfig_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppConfig): AppConfig {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_CompileResult_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompileResult): CompileResult {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_IntentExtractionResult_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IntentExtractionResult): IntentExtractionResult {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_RefinementResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RefinementResult): RefinementResult {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_RepairResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RepairResult): RepairResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_RoleHierarchyEntry_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RoleHierarchyEntry): RoleHierarchyEntry {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_SchemaGenerationResult_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SchemaGenerationResult): SchemaGenerationResult {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_SystemDesignResult_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SystemDesignResult): SystemDesignResult {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_UiPage_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UiPage): UiPage {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UiSchema_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UiSchema): UiSchema {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationError_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationError): ValidationError {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ValidationResult_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ValidationResult): ValidationResult {
    return from_candid_record_n42(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RefinementResult]): RefinementResult | null {
    return value.length === 0 ? null : from_candid_RefinementResult_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SchemaGenerationResult]): SchemaGenerationResult | null {
    return value.length === 0 ? null : from_candid_SchemaGenerationResult_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RepairResult]): RepairResult | null {
    return value.length === 0 ? null : from_candid_RepairResult_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SystemDesignResult]): SystemDesignResult | null {
    return value.length === 0 ? null : from_candid_SystemDesignResult_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IntentExtractionResult]): IntentExtractionResult | null {
    return value.length === 0 ? null : from_candid_IntentExtractionResult_n38(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ValidationResult]): ValidationResult | null {
    return value.length === 0 ? null : from_candid_ValidationResult_n41(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AppConfig]): AppConfig | null {
    return value.length === 0 ? null : from_candid_AppConfig_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: string;
    response_type: string;
    path: string;
    role: [] | [string];
    auth_required: boolean;
    request_body: [] | [string];
}): {
    method: string;
    response_type: string;
    path: string;
    role?: string;
    auth_required: boolean;
    request_body?: string;
} {
    return {
        method: value.method,
        response_type: value.response_type,
        path: value.path,
        role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.role)),
        auth_required: value.auth_required,
        request_body: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.request_body))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: [] | [string];
    components: Array<string>;
    route: string;
    auth_required: boolean;
}): {
    name: string;
    role?: string;
    components: Array<string>;
    route: string;
    auth_required: boolean;
} {
    return {
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.role)),
        components: value.components,
        route: value.route,
        auth_required: value.auth_required
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Array<string>;
    name: string;
    parent_role: [] | [string];
}): {
    permissions: Array<string>;
    name: string;
    parent_role?: string;
} {
    return {
        permissions: value.permissions,
        name: value.name,
        parent_role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.parent_role))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repair: [] | [_RepairResult];
    refinement: [] | [_RefinementResult];
    error_message: [] | [string];
    schemas: [] | [_SchemaGenerationResult];
    design: [] | [_SystemDesignResult];
    processing_time_ms: bigint;
    intent: [] | [_IntentExtractionResult];
    assumptions: Array<string>;
    success: boolean;
    validation: [] | [_ValidationResult];
    final_config: [] | [_AppConfig];
}): {
    repair?: RepairResult;
    refinement?: RefinementResult;
    error_message?: string;
    schemas?: SchemaGenerationResult;
    design?: SystemDesignResult;
    processing_time_ms: bigint;
    intent?: IntentExtractionResult;
    assumptions: Array<string>;
    success: boolean;
    validation?: ValidationResult;
    final_config?: AppConfig;
} {
    return {
        repair: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.repair)),
        refinement: record_opt_to_undefined(from_candid_opt_n20(_uploadFile, _downloadFile, value.refinement)),
        error_message: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.error_message)),
        schemas: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.schemas)),
        design: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.design)),
        processing_time_ms: value.processing_time_ms,
        intent: record_opt_to_undefined(from_candid_opt_n37(_uploadFile, _downloadFile, value.intent)),
        assumptions: value.assumptions,
        success: value.success,
        validation: record_opt_to_undefined(from_candid_opt_n40(_uploadFile, _downloadFile, value.validation)),
        final_config: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.final_config))
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    changes_made: Array<_RefinementChange>;
    config: _AppConfig;
}): {
    changes_made: Array<RefinementChange>;
    config: AppConfig;
} {
    return {
        changes_made: value.changes_made,
        config: from_candid_AppConfig_n6(_uploadFile, _downloadFile, value.config)
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    auth_schema: _AuthSchema;
    api_schema: _ApiSchema;
    ui_schema: _UiSchema;
    database_schema: _DatabaseSchema;
}): {
    auth_schema: AuthSchema;
    api_schema: ApiSchema;
    ui_schema: UiSchema;
    database_schema: DatabaseSchema;
} {
    return {
        auth_schema: value.auth_schema,
        api_schema: from_candid_ApiSchema_n8(_uploadFile, _downloadFile, value.api_schema),
        ui_schema: from_candid_UiSchema_n26(_uploadFile, _downloadFile, value.ui_schema),
        database_schema: value.database_schema
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    navigation: Array<string>;
    pages: Array<_UiPage>;
}): {
    navigation: Array<string>;
    pages: Array<UiPage>;
} {
    return {
        navigation: value.navigation,
        pages: from_candid_vec_n28(_uploadFile, _downloadFile, value.pages)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    page_name: string;
    role: [] | [string];
    layout: string;
    components: Array<_UiComponent>;
    route: string;
    auth_required: boolean;
}): {
    page_name: string;
    role?: string;
    layout: string;
    components: Array<UiComponent>;
    route: string;
    auth_required: boolean;
} {
    return {
        page_name: value.page_name,
        role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.role)),
        layout: value.layout,
        components: value.components,
        route: value.route,
        auth_required: value.auth_required
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    application_structure: Array<string>;
    role_hierarchy: Array<_RoleHierarchyEntry>;
    architecture_model: _ArchitectureModel;
    user_flows: Array<_UserFlow>;
}): {
    application_structure: Array<string>;
    role_hierarchy: Array<RoleHierarchyEntry>;
    architecture_model: ArchitectureModel;
    user_flows: Array<UserFlow>;
} {
    return {
        application_structure: value.application_structure,
        role_hierarchy: from_candid_vec_n34(_uploadFile, _downloadFile, value.role_hierarchy),
        architecture_model: value.architecture_model,
        user_flows: value.user_flows
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: Array<string>;
    role_name: string;
    parent_role: [] | [string];
}): {
    permissions: Array<string>;
    role_name: string;
    parent_role?: string;
} {
    return {
        permissions: value.permissions,
        role_name: value.role_name,
        parent_role: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.parent_role))
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    apis: Array<_ApiEndpoint>;
    entities: Array<_Entity>;
    assumptions: Array<string>;
    pages: Array<_Page>;
    roles: Array<_Role>;
    business_rules: Array<_BusinessRule>;
}): {
    apis: Array<ApiEndpoint>;
    entities: Array<Entity>;
    assumptions: Array<string>;
    pages: Array<Page>;
    roles: Array<Role>;
    business_rules: Array<BusinessRule>;
} {
    return {
        apis: from_candid_vec_n10(_uploadFile, _downloadFile, value.apis),
        entities: value.entities,
        assumptions: value.assumptions,
        pages: from_candid_vec_n14(_uploadFile, _downloadFile, value.pages),
        roles: from_candid_vec_n17(_uploadFile, _downloadFile, value.roles),
        business_rules: value.business_rules
    };
}
function from_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    errors: Array<_ValidationError>;
    is_valid: boolean;
    warnings: Array<_ValidationError>;
    config: [] | [_AppConfig];
}): {
    errors: Array<ValidationError>;
    is_valid: boolean;
    warnings: Array<ValidationError>;
    config?: AppConfig;
} {
    return {
        errors: from_candid_vec_n43(_uploadFile, _downloadFile, value.errors),
        is_valid: value.is_valid,
        warnings: from_candid_vec_n43(_uploadFile, _downloadFile, value.warnings),
        config: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.config))
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    field: [] | [string];
    message: string;
    severity: string;
    error_code: string;
}): {
    field?: string;
    message: string;
    severity: string;
    error_code: string;
} {
    return {
        field: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.field)),
        message: value.message,
        severity: value.severity,
        error_code: value.error_code
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    repairs_made: Array<_RepairAction>;
    is_valid: boolean;
    final_config: _AppConfig;
}): {
    repairs_made: Array<RepairAction>;
    is_valid: boolean;
    final_config: AppConfig;
} {
    return {
        repairs_made: value.repairs_made,
        is_valid: value.is_valid,
        final_config: from_candid_AppConfig_n6(_uploadFile, _downloadFile, value.final_config)
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    api: _ApiSchema;
    auth: _AuthSchema;
    entities: Array<_Entity>;
    database: _DatabaseSchema;
    app_name: _AppName;
    pages: Array<_Page>;
    roles: Array<_Role>;
    business_rules: Array<_BusinessRule>;
}): {
    api: ApiSchema;
    auth: AuthSchema;
    entities: Array<Entity>;
    database: DatabaseSchema;
    app_name: AppName;
    pages: Array<Page>;
    roles: Array<Role>;
    business_rules: Array<BusinessRule>;
} {
    return {
        api: from_candid_ApiSchema_n8(_uploadFile, _downloadFile, value.api),
        auth: value.auth,
        entities: value.entities,
        database: value.database,
        app_name: value.app_name,
        pages: from_candid_vec_n14(_uploadFile, _downloadFile, value.pages),
        roles: from_candid_vec_n17(_uploadFile, _downloadFile, value.roles),
        business_rules: value.business_rules
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    endpoints: Array<_ApiEndpoint>;
}): {
    endpoints: Array<ApiEndpoint>;
} {
    return {
        endpoints: from_candid_vec_n10(_uploadFile, _downloadFile, value.endpoints)
    };
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ApiEndpoint>): Array<ApiEndpoint> {
    return value.map((x)=>from_candid_ApiEndpoint_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Page>): Array<Page> {
    return value.map((x)=>from_candid_Page_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Role>): Array<Role> {
    return value.map((x)=>from_candid_Role_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UiPage>): Array<UiPage> {
    return value.map((x)=>from_candid_UiPage_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RoleHierarchyEntry>): Array<RoleHierarchyEntry> {
    return value.map((x)=>from_candid_RoleHierarchyEntry_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ValidationError>): Array<ValidationError> {
    return value.map((x)=>from_candid_ValidationError_n44(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
